from quent_core.utils.eic_utils import SHORT_NAME_EIC_PAIRS

# ENTSO-E area (EIC) codes for our bidding zones, sourced from quent_core's own
# reference table, plus two zones currently missing there.

BIDDING_ZONE_TO_ENTSOE_AREA = {
    "AT": SHORT_NAME_EIC_PAIRS["at"],
    "BE": SHORT_NAME_EIC_PAIRS["be"],
    "BG": SHORT_NAME_EIC_PAIRS["bg"],
    "CH": "10YCH-SWISSGRIDZ",
    "CZ": SHORT_NAME_EIC_PAIRS["cz"],
    "DE": SHORT_NAME_EIC_PAIRS["de_lu"],
    "DK1": SHORT_NAME_EIC_PAIRS["dk1"],
    "DK2": SHORT_NAME_EIC_PAIRS["dk2"],
    "EE": SHORT_NAME_EIC_PAIRS["ee"],
    "ES": SHORT_NAME_EIC_PAIRS["es"],
    "FI": SHORT_NAME_EIC_PAIRS["fi"],
    "FR": SHORT_NAME_EIC_PAIRS["fr"],
    "GR": SHORT_NAME_EIC_PAIRS["gr"],
    "HR": SHORT_NAME_EIC_PAIRS["hr"],
    "HU": SHORT_NAME_EIC_PAIRS["hu"],
    "IE": "10Y1001A1001A59C",
    # Italy has no single ENTSO-E area - split into 7 sub-zones, EIC codes read
    # directly off quent_core's table (short names differ from ours: it_nor,
    # it_c_nor, it_c_sud, it_sud, sici, sd, it_ca).
    "IT_NORD": SHORT_NAME_EIC_PAIRS["it_nor"],
    "IT_CNOR": SHORT_NAME_EIC_PAIRS["it_c_nor"],
    "IT_CSUD": SHORT_NAME_EIC_PAIRS["it_c_sud"],
    "IT_SUD": SHORT_NAME_EIC_PAIRS["it_sud"],
    "IT_SICI": SHORT_NAME_EIC_PAIRS["sici"],
    "IT_SARD": SHORT_NAME_EIC_PAIRS["sd"],
    "IT_CALA": SHORT_NAME_EIC_PAIRS["it_ca"],
    "LT": SHORT_NAME_EIC_PAIRS["lt"],
    "LV": SHORT_NAME_EIC_PAIRS["lv"],
    "NL": SHORT_NAME_EIC_PAIRS["nl"],
    "NO1": SHORT_NAME_EIC_PAIRS["no1"],
    "NO2": SHORT_NAME_EIC_PAIRS["no2"],
    "NO3": SHORT_NAME_EIC_PAIRS["no3"],
    "NO4": SHORT_NAME_EIC_PAIRS["no4"],
    "NO5": SHORT_NAME_EIC_PAIRS["no5"],
    "PL": SHORT_NAME_EIC_PAIRS["pl"],
    "PT": SHORT_NAME_EIC_PAIRS["pt"],
    "RO": SHORT_NAME_EIC_PAIRS["ro"],
    "SE1": SHORT_NAME_EIC_PAIRS["se1"],
    "SE2": SHORT_NAME_EIC_PAIRS["se2"],
    "SE3": SHORT_NAME_EIC_PAIRS["se3"],
    "SE4": SHORT_NAME_EIC_PAIRS["se4"],
    "SI": SHORT_NAME_EIC_PAIRS["si"],
    "SK": SHORT_NAME_EIC_PAIRS["sk"],
}
